apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-webapp
#  annotations:
#    kubernetes.io/ingress.class: ingress-nginx
spec:
  ingressClassName: nginx
  rules:
    - host: so2homelab.com
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: portfolio-service
                port:
                  number: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-api
#  annotations:
#    kubernetes.io/ingress.class: ingress-nginx
spec:
  ingressClassName: nginx
  rules:
    - host: band.so2homelab.com
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: webapp-service
                port:
                  number: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-api
#  annotations:
#    kubernetes.io/ingress.class: ingress-nginx

spec:
  ingressClassName: nginx
  rules:
    - host: api.so2homelab.com
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: fastapi-service
                port:
                  number: 5000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: postgresql-ingres
#  annotations:
#    kubernetes.io/ingress.class: nginx
#spec:
#  ingressClassName: nginx
#  rules:
#    - host: postgre.so2homelab.com
#      http:
#        paths:
#          - pathType: Prefix
#            path: "/"
#            backend:
#              service:
#                name: postgres-service
#                port:
#                  number: 5432