apiVersion: apps/v1
kind: Deployment
metadata:
  name: portfolio-deployment
  labels:
    app: portfolio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: portfolio
  template:
    metadata:
      labels:
        app: portfolio
    spec:
      containers:
        - name: portfoliocontainer
          image: so2harbor.com:6000/library/portfolio:latest
          ports:
            - containerPort: 8080
      imagePullSecrets:
        - name: regcred


---
apiVersion: v1
kind: Service
metadata:
  name: portfolio-service
spec:
  type: NodePort
  selector:
    app: portfolio
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30300
#---
#apiVersion: v1
#kind: Service
#metadata:
#  name: portfolio-service
#spec:
#  type: LoadBalancer
#  selector:
#    app: portfolio
#  ports:
#    - protocol: TCP
#      port: 8080
#      targetPort: 8080
#  clusterIP: 10.99.163.231
