---
- hosts: all
  become: true
  tasks:

  - name : install apache2 and php support on ubuntu
    apt:
      name:
        - apache2
        - libapache2-mod-php
      state: latest
      update_cache: yes
    when: ansible_distribution in ["Debian", "Ubuntu"]
# for centos
  - name : install apache2 and php support  on Centos
    dnf:
        name:
          - httpd
          - php
        state: latest
        update_cache: yes
    when: ansible_distribution == "CentOS"

