---
- hosts: kubernetes_servers
#   become: true
  tasks:
#   - name: install updates
#     apt:
#         upgrade: dist
#         update_cache: yes
#   - name : install build-essential
#     apt:
#       name:
#         - build-essential
#       state: latest
#       update_cache: yes
#   - name: install homebrew with script
#     get_url: url=https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh dest=/root/tmp
#   - name: Changing perm of "/home/so2/tmp/install.sh", adding "+rwx"
#     file:
#       path: /root/tmp/install.sh
#       state: file
#       owner: root
#       group: root
#       mode: 0755
  - name: run install.sh script
    expect:
        script: install_brew.sh
        responses:
          '[sudo] password for so2': "7668"
          'Press RETURN/ENTER to continue or any other key to abort': ""
        register: console

  - name: display msg
    debug: msg="{{console.stdout}}"

