---
- hosts: all
  become: true
  tasks:
  - name: update repository index
    apt:
      update_cache: yes
#     when: ansible_distribution == "Ubuntu"
    when: ansible_distribution in ["Debian", "Ubuntu"]
  - name : install apache2 package
    apt:
      name: apache2
      state: latest
    when: ansible_distribution in ["Debian", "Ubuntu"]
  - name : install php support for apache2
    apt:
      name: libapache2-mod-php
      state: latest
    when: ansible_distribution in ["Debian", "Ubuntu"]
# for centos
- name: update repository index for centos
    dnf:
      update_cache: yes
#     when: ansible_distribution == "Ubuntu"
    when: ansible_distribution == "CentOS"
  - name : install apache2 package on Centos
    dnf:
      name: httpd
      state: latest
    when: ansible_distribution == "CentOS"
  - name : install php support for apache2 on Centos
    dnf:
      name: phd
      state: latest
    when: ansible_distribution == "CentOS"

