---
- hosts: kubernetes_servers
  become: true
  tasks:
  - name: downloading tar
    shell: curl -Lo lazygit.tar.gz "https://github.com/jesseduffield/lazygit/releases/latest/download/lazygit_0.36.0_Linux_x86_64.tar.gz"
  - name: extracting tar
    shell: sudo tar xf lazygit.tar.gz -C /usr/local/bin lazygit
