apiVersion: apps/v1
kind: Deployment
metadata:
  name: registry-test-deployment
  labels:
    app: registry-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: registry-test
  template:
    metadata:
      labels:
        app: registry-test
    spec:
      containers:
        - name: registry-test-container
          image: so2harbor.com:6000/library/docker_registry_test:latest
      imagePullSecrets:
        - name: regcred

